name: Docker Image CI

on:
  repository_dispatch:
    types: rebuild
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo 'Hello'
